### ISSUE TITLE
Dump cannot be completed?

### ISSUE THREAD

**Issue by mekhalleh** [csababarta/ntdsxtract#16]
Hello,

I encounter always the same error with always the same username.
The extraction is stopped...

Dump from Microsoft Windows 2008 R2
Have you an idea ?

Thanks in advance.

Traceback (most recent call last):
  File "/usr/local/src/ntdsxtract/dsusers.py", line 513, in <module>
    processUser(user)
  File "/usr/local/src/ntdsxtract/dsusers.py", line 97, in processUser
    sys.stdout.write(str(user))
  File "/usr/local/src/ntdsxtract/ntds/dsobjects.py", line 378, in __str__
    ancestors = self.getAncestors(self.DB)
  File "/usr/local/src/ntdsxtract/ntds/dsobjects.py", line 108, in getAncestors
    ancestor = dsObject(dsDatabase, ancestorid)
  File "/usr/local/src/ntdsxtract/ntds/dsobjects.py", line 57, in __init__
    raise BaseException
BaseException

**Comment by ophc** [comment]
same problem here, with 1.3.1 
==============Traceback (most recent call last):
  File "/opt/ntdsxtract-master/dsusers.py", line 505, in <module>
    processUser(user)
  File "/opt/ntdsxtract-master/dsusers.py", line 97, in processUser
    sys.stdout.write(str(user))
  File "/opt/ntdsxtract-master/ntds/dsobjects.py", line 378, in __str__
    ancestors = self.getAncestors(self.DB)
  File "/opt/ntdsxtract-master/ntds/dsobjects.py", line 108, in getAncestors
    ancestor = dsObject(dsDatabase, ancestorid)
  File "/opt/ntdsxtract-master/ntds/dsobjects.py", line 57, in __init__
    raise BaseException
BaseException

**Comment by mekhalleh** [comment]
Corrected unofficially, I have sent you a pull request.

https://github.com/csababarta/ntdsxtract/pull/17

**Comment by ktneely** [comment]
@mekhalleh nice fix, I just tested it with my setup and it worked perfectly on files pulled from a shadow copy of 2012 AD server.
