### ISSUE TITLE
Error in sys.excepthook:

### ISSUE THREAD

**Issue by chukytron** [csababarta/ntdsxtract#31]
hi i have tried to run the following in my kali vm by aws, and found the following issue:

/usr/share/doc/python3-impacket/examples/ntdsxtract# python3 dsusers.py /usr/local/bin/ntds.dit.export/datatable.4 /usr/local/bin/ntds.dit.export/link_table.6 --lmoutfile lm.out --ntoutfile nt.out --syshive SYSTEM.bin --passwordhashes --pwdformat john
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/doc/python3-impacket/examples/ntdsxtract/ntds/__init__.py", line 31, in simple_exception
    sys.stderr.write("[!] Error!", value, "\n")
TypeError: write() takes exactly one argument (3 given)

Original exception was:
Traceback (most recent call last):
  File "dsusers.py", line 27, in <module>
    from ntds.dsdatabase import *
  File "/usr/share/doc/python3-impacket/examples/ntdsxtract/ntds/dsdatabase.py", line 370
    else:
        ^
TabError: inconsistent use of tabs and spaces in indentation

can someone please help on solving this ?
thanks so much.

**Comment by ConsT27** [comment]
use python2
