### ISSUE TITLE
TypeError: function takes exactly 1 argument (3 given) when processing principal

### ISSUE THREAD

**Issue by franckc2** [csababarta/ntdsxtract#34]
Hi,

here is the line I am using :
**c:\Python27\python.exe  C:\zgms\TEMPO\2NTDSX\dskeytab.py .\datatable.4 .\link_table.5 .\SYSTEM C:\zgms\TEMPO C:\zgms\TEMPO\keytab.key**

The first part when through easily but I get stuck when it wants to create the KAYTAB file.

[+] Initialising engine...
[+] Loading saved map files (Stage 1)...
[+] Loading saved map files (Stage 2)...
Processing principal AD03-DTC$.
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\zgms\TEMPO\2NTDSX\ntds\__init__.py", line 31, in simple_exception
    sys.stderr.write("[!] Error!", value, "\n")
TypeError: function takes exactly 1 argument (3 given)

Original exception was:
Traceback (most recent call last):
  File "C:\zgms\TEMPO\2NTDSX\dskeytab.py", line 263, in <module>
    dsAddPrincipalEntries(principal, keytabFile)
  File "C:\zgms\TEMPO\2NTDSX\dskeytab.py", line 145, in dsAddPrincipalEntries
    kerberosKeys = dsGetPrincipalKerberosKeys(principal)
  File "C:\zgms\TEMPO\2NTDSX\dskeytab.py", line 163, in dsGetPrincipalKerberosKeys
    creds = principal.getSupplementalCredentials()
  File "C:\zgms\TEMPO\2NTDSX\ntds\dsobjects.py", line 254, in getSupplementalCredentials
    return dsSupplCredentials(tmpdec)
  File "C:\zgms\TEMPO\2NTDSX\ntds\dsobjects.py", line 506, in __init__
    self.ParseUserProperties(text)
  File "C:\zgms\TEMPO\2NTDSX\ntds\dsobjects.py", line 533, in ParseUserProperties
    assert reserved1 == 0
AssertionError

Since I get through the first part, I guess I am doing at least part of it right.

Thanks for you help.

**Comment by lzzbb** [comment]
+1

**Comment by CppXL** [comment]
you can delete that line, look like this
```python
def simple_exception(type, value, traceback):
    #sys.stderr.write( value)
    sys.exit(1)
```

**Comment by qihu0808** [comment]
> 

i have the same issue ，but it is not working

**Comment by CppXL** [comment]
> 

show u issue

**Comment by qihu0808** [comment]
> > 
> 
> show u issue

└─$ python2 ../ntdsxtract/dskeytab.py ../ntds.dit.export/datatable.4 ../ntds.dit.export/link_table.7 ../system.hive ~/ntdsxtract/ 1.keytab

[+] Initialising engine...
[+] Loading saved map files (Stage 1)...
[+] Loading saved map files (Stage 2)...
Processing principal Administrator.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/kali/ntdsxtract/ntds/__init__.py", line 31, in simple_exception
    sys.stderr.write("[!] Error!", value, "\n")
TypeError: function takes exactly 1 argument (3 given)

Original exception was:
Traceback (most recent call last):
  File "../ntdsxtract/dskeytab.py", line 239, in <module>
    dsAddPrincipalEntries(principal, keytabFile)
  File "../ntdsxtract/dskeytab.py", line 145, in dsAddPrincipalEntries
    kerberosKeys = dsGetPrincipalKerberosKeys(principal)
  File "../ntdsxtract/dskeytab.py", line 163, in dsGetPrincipalKerberosKeys
    creds = principal.getSupplementalCredentials()
  File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 254, in getSupplementalCredentials
    return dsSupplCredentials(tmpdec)
  File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 506, in __init__
    self.ParseUserProperties(text)
  File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 533, in ParseUserProperties
    assert reserved1 == 0
AssertionError

is it  the different formats of   ntds.dit ?  my dc is win2016

**Comment by qihu0808** [comment]
> > > 
> > 
> > 
> > show u issue
> 
> └─$ python2 ../ntdsxtract/dskeytab.py ../ntds.dit.export/datatable.4 ../ntds.dit.export/link_table.7 ../system.hive ~/ntdsxtract/ 1.keytab
> 
> [+] Initialising engine... [+] Loading saved map files (Stage 1)... [+] Loading saved map files (Stage 2)... Processing principal Administrator. Error in sys.excepthook: Traceback (most recent call last): File "/home/kali/ntdsxtract/ntds/**init**.py", line 31, in simple_exception sys.stderr.write("[!] Error!", value, "\n") TypeError: function takes exactly 1 argument (3 given)
> 
> Original exception was: Traceback (most recent call last): File "../ntdsxtract/dskeytab.py", line 239, in dsAddPrincipalEntries(principal, keytabFile) File "../ntdsxtract/dskeytab.py", line 145, in dsAddPrincipalEntries kerberosKeys = dsGetPrincipalKerberosKeys(principal) File "../ntdsxtract/dskeytab.py", line 163, in dsGetPrincipalKerberosKeys creds = principal.getSupplementalCredentials() File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 254, in getSupplementalCredentials return dsSupplCredentials(tmpdec) File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 506, in **init** self.ParseUserProperties(text) File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 533, in ParseUserProperties assert reserved1 == 0 AssertionError
> 
> is it the different formats of ntds.dit ? my dc is win2016
with your solution，it is disable the error debug，and get a same result

└─$ python2 ../ntdsxtract/dskeytab.py ../ntds.dit.export/datatable.4 ../ntds.dit.export/link_table.7 ../system.hive ~/ntdsxtract/ 1.keytab

[+] Initialising engine...
[+] Loading saved map files (Stage 1)...
[+] Loading saved map files (Stage 2)...
Processing principal Administrator.

┌──(mytest)─(kali㉿kali)-[~/mytest]
└─$ ktutil -k 1.keytab list                                                                                                                                                                               1 ⨯
1.keytab:

Vno  Type  Principal  Aliases

**Comment by CppXL** [comment]
> > > > 
> > > 
> > > 
> > > show u issue
> > 
> > 
> > └─$ python2 ../ntdsxtract/dskeytab.py ../ntds.dit.export/datatable.4 ../ntds.dit.export/link_table.7 ../system.hive ~/ntdsxtract/ 1.keytab
> > [+] Initialising engine... [+] Loading saved map files (Stage 1)... [+] Loading saved map files (Stage 2)... Processing principal Administrator. Error in sys.excepthook: Traceback (most recent call last): File "/home/kali/ntdsxtract/ntds/**init**.py", line 31, in simple_exception sys.stderr.write("[!] Error!", value, "\n") TypeError: function takes exactly 1 argument (3 given)
> > Original exception was: Traceback (most recent call last): File "../ntdsxtract/dskeytab.py", line 239, in dsAddPrincipalEntries(principal, keytabFile) File "../ntdsxtract/dskeytab.py", line 145, in dsAddPrincipalEntries kerberosKeys = dsGetPrincipalKerberosKeys(principal) File "../ntdsxtract/dskeytab.py", line 163, in dsGetPrincipalKerberosKeys creds = principal.getSupplementalCredentials() File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 254, in getSupplementalCredentials return dsSupplCredentials(tmpdec) File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 506, in **init** self.ParseUserProperties(text) File "/home/kali/ntdsxtract/ntds/dsobjects.py", line 533, in ParseUserProperties assert reserved1 == 0 AssertionError
> > is it the different formats of ntds.dit ? my dc is win2016
> > with your solution，it is disable the error debug，and get a same result
> 
> └─$ python2 ../ntdsxtract/dskeytab.py ../ntds.dit.export/datatable.4 ../ntds.dit.export/link_table.7 ../system.hive ~/ntdsxtract/ 1.keytab
> 
> [+] Initialising engine... [+] Loading saved map files (Stage 1)... [+] Loading saved map files (Stage 2)... Processing principal Administrator.
> 
> ┌──(mytest)─(kali㉿kali)-[~/mytest] └─$ ktutil -k 1.keytab list 1 ⨯ 1.keytab:
> 
> Vno Type Principal Aliases

I try it on windows server 2008 export files, it's working. but use it on windows server2016/2019, got an error


maybe, on windows server 2016/2019 the file format has been change. so u can use server 2008 to decrypt kerberos
